use_frameworks!

target 'KEPNetwork_Example' do
  pod 'KEPNetwork', :path => '../'

  target 'KEPNetwork_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
